name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Convert GitHub actor to lower case
      id: actor-lowercase
      run: echo "::set-output name=actor::$(echo ${{ github.actor }} | awk '{print tolower($0)}')"

    - name: Set up Docker Buildx
	    uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
	    uses: docker/login-action@v3
	    with:
		    registry: ghcr.io
		    username: ${{ github.actor }}
		    password: ${{ secrets.CR_PAT }}

    - name: Build and push Docker image
	    uses: docker/build-push-action@v2
	    with:
		    context: .
		    file: ./Dockerfile
		    push: true
		    tags: ghcr.io/${{ steps.actor-lowercase.outputs.actor }}/holbertonschool-higher_level_programming:latest